### ISSUE TITLE
Sending all information (normally fetched by endpoint) when endpoint is omitted

### ISSUE THREAD

**Issue by tbranyen** [bocoup/email#4]
Mouthful of a title, but after talking with @tafsiri I think it would be ideal to be able to omit the `endpoint` property (in some cases) and opt for passing data directly at the time of scheduling a poller.

Effectively identical to the endpoint except one less request.

**Comment by tkellen** [comment]
:+1:

**Comment by tkellen** [comment]
Actually... the point of the poller is that the data which needs to be sent is dynamic. What's the use case where you would have a poller sending an identical message repeatedly? Isn't this just a re-statement of #5?

The example I've been using is that we want to send a reminder to a person who is supposed to review a time off request if they don't review it within 5 days of submission.

Assume the time off request is reviewed... I don't want to remove that queued reminder when the review happens because that means our API has to keep track of emails queued in the email system. Instead, I want to flip the responsibility and have the email system poll daily for time off requests which have criteria that say they should be reviewed.

**Comment by tbranyen** [comment]
@tafsiri had mentioned that in the one off cases, if he couldn't just post the data he already has, he probably wouldn't use the system.  I'm inclined to agree.  If you already have the template, email addresses, data, etc. and you just want to schedule it in the future, without having to worry about the hassle of setting up and securing an endpoint, I think this would be ideal.  It shouldn't be anything overwhelming code-wise to implement this.

**Comment by tkellen** [comment]
Gotcha.  So... isn't this issue a restatement of #5, then?

**Comment by tbranyen** [comment]
No, because #5 could be used with an endpoint.

**Comment by tkellen** [comment]
Ah, of course. I was caught up on it being called a poller and being confused why you'd send the same fixed data at multiple times. I see now that if you add an expiration to pollers and allow arbitrary data to be included they can both use the same primitives to work.

**Comment by tbranyen** [comment]
This has been resolved, you can send data and templates by specifying the appropriate type.

Static data:

``` json
{
  "data": {
    "type": "json",
    "value": { "some": "fun", "json": "data" }
  }
}
```

Templates can be embedded with:

``` json
{
  "template": {
    "type": "html",
    "value": "{{ data.hi }}"
  }
}
```
